const Data = [
  {
    id: 1,
    text: "Bihar Home Guard Recruitment 2025 Download Admit Card for 15000 Post",
    postDate: "24 April 2025 | 01:02 PM",
    shortInfo:
      "Bihar Home Guard Department has released the advertisement Bihar Home Guard HG 2025. Those Candidates Are Interested with Bihar Home Guard Vacancy Can Download Admit Card. For other information related to Bihar Home Guard 2025 recruitment like age limit, qualification, pay scale and all other information read the advertisement and then apply.",
    importantDates: {
      applicationBegin: "27/03/2025",
      lastDateApplyOnline: "16/04/2025",
      payExamFeeLastDate: "16/04/2025",
      examDate: "As per Schedule",
      admitCardAvailable: "24/04/2025",
    },
    applicationFee: {
      general: "200/-",
      obc: "200/-",
      ews: "200/-",
      sc: "100/-",
      st: "100/-",
      female: "100/-",
      paymentMode:
        "Pay the Examination Fee Through Debit Card, Credit Card, Net Banking or Pay Offline Fee Payment Through E Challan Mode Only",
    },
    ageLimit: {
      minimumAge: "19 Years",
      maximumAge: "40 Years",
      ageRelaxation:
        "Extra as per Bihar Home Guard Advt No. 01/2025 Recruitment 2025",
    },
    vacancyDetails: {
      totalPost: 15000,
      eligibility:
        "Bihar Domicile, 10+2 Inter Exam Passed from Any Recognized Board in India.",
    },
    districtWiseVacancy: [
      { district: "Patna", totalPost: 1479 },
      { district: "Chapra", totalPost: 690 },
      { district: "Nalanda", totalPost: 812 },
      { district: "Siwan", totalPost: 234 },
      { district: "Rohtas", totalPost: 559 },
      { district: "Gopalganj", totalPost: 394 },
      { district: "Bhojpur", totalPost: 511 },
      { district: "Muzaffarpur", totalPost: 296 },
      { district: "Buxar", totalPost: 312 },
      { district: "Sitamarhi", totalPost: 439 },
      { district: "Kaimur/Bhabua", totalPost: 241 },
      { district: "Sheohar", totalPost: 78 },
      { district: "Gaya", totalPost: 909 },
      { district: "P. Champaran", totalPost: 311 },
      { district: "Jahanabad", totalPost: 317 },
      { district: "East Champaran", totalPost: 474 },
      { district: "Aurangabad", totalPost: 217 },
      { district: "Vaishali", totalPost: 476 },
      { district: "Nawada", totalPost: 361 },
      { district: "Darbhanga", totalPost: 741 },
      { district: "Madhubani", totalPost: 607 },
      { district: "Munger", totalPost: 171 },
      { district: "Samastipur", totalPost: 731 },
      { district: "Lakhisarai", totalPost: 123 },
      { district: "Saharsa", totalPost: 74 },
      { district: "Sheikhpura", totalPost: 192 },
      { district: "Supaul", totalPost: 144 },
      { district: "Khagaria", totalPost: 111 },
      { district: "Madhepura", totalPost: 193 },
      { district: "Jamui", totalPost: 257 },
      { district: "Bhagalpur", totalPost: 666 },
      { district: "Begusarai", totalPost: 422 },
      { district: "Banka", totalPost: 294 },
      { district: "Kishanganj", totalPost: 280 },
      { district: "Purnia", totalPost: 280 },
      { district: "Katihar", totalPost: 484 },
      { district: "Araria", totalPost: 141 },
    ],
    physicalEligibility: {
      male: {
        height: "5 Feet 4 Inch (162.56 CMS)",
        chest: "31 Inch (79 CMS)",
        running: "1.6 Km in 6 Minutes",
        golaFek: "16 Pond Gola Through 16 Feet",
        highJump: "04 Feet",
        longJump: "12 Feet",
      },
      female: {
        height: "153 CMS",
        chest: "Not Available",
        running: "800 Meter in 5 Minutes",
        golaFek: "12 Pond Gola Through 10 Feet",
        highJump: "03 Feet",
        longJump: "09 Feet",
      },
    },
    howToApply: [
      "Bihar Home Guard Recruitment Advt No 01/2025. Candidate Can Apply Between 27/03/2025 to 16/04/2025.",
      "Candidate Read the Notification Before Apply the Recruitment Application Form in Bihar Home Guard Latest 01/2025 Recruitment Online Form 2025.",
      "Kindly Check and Collect the All Document - Eligibility, ID Proof, Address Details, Basic Details.",
      "Kindly Ready Scan Document Related to Recruitment Form - Photo, Sign, ID Proof, Etc.",
      "Before Submit the Application Form Must Check the Preview and All Column Carefully.",
      "If Candidate Required to Paying the Application Fee Must Submit. If You have Not the Required Application Fees Your Form is Not Completed.",
      "Take A Print Out of Final Submitted Form.",
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Notification", url: "#" },
    ],
  },
  {
    id: 2,
    text: "NTA NEET UG Admissions 2025 Exam City Details for MBBS / BDS Course",
    postDate: "23 April 2025 | 06:54 PM",
    shortInfo:
      "National Testing Agency (NTA) has released the National Eligibility Cum Entrance Test NEET UG 2025 online application for admission 2025 will start from 07 February 2025 and the last date to apply will be 07 March 2025. Various Institution are participating in NEET UG 2025, candidates should read the information brochure for all the information related to the entrance exam like syllabus, eligibility, age limit, placement, fees, college information and other types of information and then apply.",
    importantDates: {
      applicationBegin: "07/02/2025",
      lastDateApplyOnline: "07/03/2025",
      lastDateOnlinePayment: "07/03/2025",
      correctionDate: "09-11 March 2025",
      examDate: "04/05/2025 (Sunday)",
      examCityAvailable: "23/04/2025",
      admitCardAvailable: "01/05/2025",
      resultDeclared: "14/06/2025",
    },
    applicationFee: {
      general: "1700/-",
      ewsObc: "1600/-",
      scStPh: "1000/-",
      outsideIndia: "9500/-",
      paymentMode:
        "Pay the Examination Fee Through E Challan Offline Mode or Pay the Exam Fee Through Online Debit Card, Credit Card or Net Banking Fee Mode",
    },
    eligibility:
      "Passed 10+2 Intermediate Exam with Physics, Chemistry, Biology PCB Group of Subjects in Any Recognized Board in India. For More Details Kindly See the Full Information Brochure or Read the Code Wise Eligibility Details.",
    ageLimit: {
      minimumAge: "17 Years",
      maximumAge: "No Limit",
      bornOnOrBefore: "31.12.2008",
      ageRelaxation: "Extra as per Rules",
    },
    importantLinks: [
      { label: "Check Exam City Details", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "For Correction / Edit Form", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "How to Fill Form (Video Hindi)", url: "#" },
      { label: "Download Correction Notice", url: "#" },
      { label: "Download Information Brochure", url: "#" },
    ],
  },
  {
    id: 3,
    text: "Social Welfare Department SWD UP IAS / PCS Free Coaching Admissions 2025 Download Admit Card",
    postDate: "23 April 2025 | 05:36 PM",
    shortInfo:
      "Social Welfare Department, SWD Uttar Pradesh has released UP IAS PCS Free Coaching Admissions 2025 Notification. Those candidates who are interested in this UP IAS PCS Free Coaching Admissions 2025 Entrance Exam can Download Admit Card. Read the notification for SWD Free Coaching Admission Test, eligibility, Coaching Details information, Document Required, age limit, How to Apply and all other information.",
    importantDates: {
      applicationBegin: "25/02/2025",
      lastDateApplyOnline: "31/03/2025",
      lastDateCompleteForm: "31/03/2025",
      examDate: "27/04/2025",
      admitCardAvailable: "23/04/2025",
      resultDeclared: "15/05/2025",
      freeCoachingStart: "July 2025",
    },
    applicationFee: {
      obc: "0/-",
      scStPh: "0/-",
      note: "NO Application Fee for the Online Registration Only Fill the Online Application Form.",
    },
    ageLimit: {
      iasMinimumAge: "21 Years",
      uppscPreMinimumAge: "21 Years",
    },
    eligibility: {
      domicile:
        "Only OBC / SC / ST Uttar Pradesh Domicile Candidates Are Eligible",
      income: "Annual Income Less than 6 Lakh Per Yr",
      education: "Bachelor Degree in Any Stream",
    },
    documentRequired: [
      "High School Certificate Scan Copy",
      "Graduate Certificate Scan Copy",
      "Photo ID Proof (Aadhar / Pan / DL / Etc) Scan Copy",
      "Recently Passport Size Photo and Signature",
      "Any Other Supporting Documents",
    ],
    centerWiseSeats: [
      {
        center:
          "Chhatrapati Shahu Ji Maharaj Shodh Avam Prasikshan Sansthan Bhagidari Bhawan, Lucknow",
        totalSeats: 250,
      },
      {
        center:
          "Adarsh Purva Prashikshan Kendra Aliganj, Lucknow (Only for Female)",
        totalSeats: 150,
      },
      {
        center: "IAS / PSC Coaching Center, Hapur Ghaziabad",
        totalSeats: 200,
      },
      {
        center: "Sant Ravidas IAS / PSC Coaching Center Varanasi",
        totalSeats: 100,
      },
      {
        center: "Dr B.R. Ambedkar Coaching, Agra",
        totalSeats: 100,
      },
      {
        center: "Dr. B.R. Ambedkar Coaching, Aligarh",
        totalSeats: 100,
      },
      {
        center: "Prayagraj Center",
        totalSeats: 50,
      },
      {
        center: "Gorakhpur Center",
        totalSeats: 100,
      },
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Notice", url: "#" },
      { label: "Download Syllabus", url: "#" },
    ],
  },
  {
    id: 4,
    text: "NTA National Council of Hotel Management NCHMJEE 2025 Admissions Admit Card",
    postDate: "23 April 2025 | 05:34 PM",
    shortInfo:
      "National Testing Agency (NTA) has released the National Council of Hotel Management NCHM JEE 2025 online application for admission 2025 will start from 16 December 2024 and the last date to apply will be 15 March 2025. Various Institution are participating in NCHMJEE 2025, candidates should read the information brochure for all the information related to the entrance exam like syllabus, eligibility, age limit, placement, fees, college information and other types of information and then apply.",
    importantDates: {
      applicationBegin: "16/12/2024",
      lastDateApplyOnline: "15/03/2025 upto 05 PM",
      lastDatePayExamFee: "15/03/2025",
      correctionDate: "17/03/2025",
      examDate: "27/04/2025",
      examCityAvailable: "19/04/2025",
      admitCardAvailable: "23/04/2025",
      resultAnnounced: "Notified Soon",
    },
    applicationFee: {
      generalObcNcl: "1000/-",
      ews: "700/-",
      scStPh: "450/-",
      paymentMode:
        "Pay the Exam Fee Through Online Debit Card, Credit Card, Net Banking or Pay Through Offline E Challan Fee Mode Only.",
    },
    admissionDetails: {
      courseName:
        "B.Sc. (Hospitality & Hotel Administration) B.Sc. HHA Admission 2025",
      eligibility:
        "Passed / Appearing 10+2 Intermediate Exam with English as a Compulsory Subject. For More Eligibility Details, College List and Other Information Must Read the Notification.",
    },
    examCityDetails: [
      {
        state: "Uttar Pradesh",
        cities: [
          "Agra",
          "Aligarh",
          "Prayagraj",
          "Ballia",
          "Bareilly",
          "Basti",
          "Faizabad",
          "Ghaziabad",
          "Gorakhpur",
          "Jhansi",
          "Kanpur",
          "Lucknow",
          "Meerut",
          "Moradabad",
          "Noida",
          "Raebareili",
          "Varanasi",
        ],
      },
      {
        state: "Uttrakhand",
        cities: ["Dehradun", "Haldwani", "Roorkee"],
      },
      {
        state: "Rajasthan",
        cities: ["Jaipur", "Kota", "Udaipur", "Jodhpur"],
      },
      {
        state: "Madhya Pradesh",
        cities: ["Bhopal", "Gwalior", "Indore", "Jabalpur", "Sagar"],
      },
      {
        state: "Haryana",
        cities: ["Faridabad", "Hisar", "Gurugram"],
      },
      {
        state: "Delhi",
        cities: ["Delhi / NCR"],
      },
      {
        state: "Bihar",
        cities: ["Bhagalpur", "Darbhanga", "Gaya", "Muzaffarpur", "Patna"],
      },
      {
        state: "Pan India",
        cities: ["And Other Various Exam Centers"],
      },
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Check Exam City", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Date Extended Notice", url: "#" },
      { label: "Download Notification", url: "#" },
    ],
  },
  {
    id: 5,
    text: "UPSSSC Enforcement Constable Recruitment 2023 Pay Mains Exam Fee 2025 for 477 Post",
    postDate: "22 April 2025 | 07:02 PM",
    shortInfo:
      "Uttar Pradesh Subordinate Service Selection Commission (UPSSSC) has released the Pravartan Sipahi recruitment advertisement for 477 posts. Those candidates who are Enrolled with Vacancy Can Check Eligibility Result. Read the notification for recruitment eligibility, post information, selection procedure, age limit, pay scale and all other information.",
    importantDates: {
      applicationBegin: "07/07/2023",
      lastDateRegistration: "28/07/2023",
      feePaymentLastDate: "28/07/2023",
      correctionLastDate: "04/08/2023",
      syllabusAvailable: "12/10/2023",
      eligibilityResultAvailable: "06/02/2024",
      payMainsExamFeesNotice: "22/04/2025",
      examDate: "11/05/2025",
      admitCardAvailable: "Before Exam",
    },
    applicationFee: {
      generalObcEws: "25/-",
      scSt: "25/-",
      ph: "25/-",
      paymentMode:
        "Pay the Examination Fee Through State Bank of India SBI I Collect Fee Mode or Pay the Exam Fee Through E Challan",
    },
    ageLimit: {
      minimumAge: "18 Years",
      maximumAge: "25 Years",
      ageRelaxation:
        "Extra as per UPSSSC UP Enforcement Constable Recruitment Advt No. 04/2023 Rules",
    },
    vacancyDetails: {
      totalPost: 477,
      eligibility:
        "UPSSSC PET 2022 Score Card. 10+2 Intermediate Exam in Any Recognized Board in India.",
    },
    physicalEligibility: {
      height: {
        male: "168 CMS, ST: 160 CMS",
        female: "152 CMS, ST: 147 CMS",
      },
      chest: {
        male: "79-84 CMS, ST: 77-82 CMS",
      },
      running: {
        male: "4.8 Km in 27 Minutes",
        female: "2.4 KM in 16 Minutes",
      },
    },
    categoryWiseVacancy: [
      { category: "General", totalPost: 225 },
      { category: "EWS", totalPost: 47 },
      { category: "OBC", totalPost: 99 },
      { category: "SC", totalPost: 93 },
      { category: "ST", totalPost: 13 },
    ],
    howToApply: [
      "There are 02 types to apply online for UPSSSC Enforcement Constable Recruitment Advt No. 04-Exam/2023 Recruitment 2023.",
      "First: In this, the candidate will have to login with his personal information, the information that has to be given is: PET Registration Number, Date of Birth, Gender, Domicile and Category.",
      "Second: In this, the candidate will have to login through his OTP, the information that has to be given is: UPSSSC PET 2022 Registration Number and OTP Password.",
      "After login, the complete information of the candidate, his photo and signature will also be visible, the candidate will have to fill the information related to the post he is asking for and the application fee: Rs.25/- will have to be paid.",
      "Kindly Check and Collect the All Document - Eligibility, ID Proof, Address Details, Basic Details.",
      "Kindly Ready Scan Document Related to Recruitment Form - Photo, Sign, ID Proof, Etc.",
      "Before Apply Online / Submit Application Form Must Check the Preview and All Column Carefully.",
      "Take A Print Out of Final Submitted Form.",
    ],
    importantLinks: [
      { label: "Pay Mains Exam Fee", url: "#" },
      { label: "Download Fee Payment Notice", url: "#" },
      { label: "Download Exam Notice", url: "#" },
      { label: "Download Eligibility Result", url: "#" },
      { label: "How to Check Eligibility Result (Video Hindi)", url: "#" },
      { label: "Download Eligibility Result Notice", url: "#" },
      { label: "Download Syllabus", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Notification", url: "#" },
    ],
  },
  {
    id: 8,
    text: "NTA National Common Entrance Test NCET 2025 Admissions Admit Card",
    postDate: "26 April 2025 | 11:55 AM",
    shortInfo:
      "National Testing Agency (NTA) has released the National Common Entrance Test NCET 2025 online application for admission 2025 will start from 20 February 2025 and the last date to apply will be 31 March 2025. Various Institution are participating in NCET 2025, candidates should read the information brochure for all the information related to the entrance exam like syllabus, eligibility, age limit, placement, fees, college information and other types of information and then apply.",
    importantDates: {
      applicationBegin: "20/02/2025",
      lastDateApplyOnline: "31/03/2025",
      lastDateOnlinePayment: "31/03/2025",
      correctionDate: "As per Schedule",
      examDate: "29/04/2025",
      examCityAvailable: "22/04/2025",
      admitCardAvailable: "26/04/2025",
      resultDeclared: "Notified Soon",
    },
    applicationFee: {
      general: "1200/-",
      ewsObc: "1000/-",
      scStPh: "650/-",
      paymentMode:
        "Pay the Examination Fee Through E Challan Offline Mode or Pay the Exam Fee Through Online Debit Card, Credit Card or Net Banking Fee Mode",
    },
    ageLimit: {
      note: "No Age Limit in National Common Entrance Test NCET 2025. For More Information Read the Information Brochure.",
    },
    admissionDetails: {
      examName:
        "National Common Entrance Test NCET 2025 Admission To B.Ed 4 Year Integrated Teacher Education Programme ITEP in Selection Central / State University / IITs / NITs / RIEs and Govt Colleges.",
      eligibility:
        "Passed / Appearing 10+2 Intermediate Exam in Any Recognized Board in India.",
    },
    participatingUniversities: [
      "Aligarh Muslim University AMU",
      "Central University of Haryana",
      "Central University of Kashmir",
      "Central University Kerala",
      "Central University of Rajasthan",
      "Central University of Tamil Nadu",
      "Chaudhary Devi Lal University",
      "Maharshi Dayanand University MDU",
      "Dr. B R Ambedkar National Institute of Technology Lidhran Bidhipur",
      "Dr B R Ambedkar University Etcherla Main Road Srikakulam, Andhra Pradesh",
      "Dr. Hari Singh Gour Vishwavidyalaya",
      "Gautam Buddha University",
      "Government College of Education, Chandigarh",
      "Government Degree College, Mancherial Telangana",
      "Guru Nanak Dev University",
      "Hemvati Nandan Bahaguna Garhwal University",
      "Indian Institute of Technology Kharagpur West Bengal",
      "Indian Institute of Technology Bhubaneshwar",
      "Indira Gandhi National Open University IGNOU",
      "Budelkhand University",
      "Kiang Nangbah Government College Meghalaya",
      "Kumaun University Sleepy Hollow",
      "Maharaja Purna Chandra Autonomous College Odisha",
      "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya",
      "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya Rajaula MP",
      "Mata Sundri College for Women",
      "Maulana Azad National Urdu University",
      "National Sanskrit University",
      "Rajiv Gandhi University",
      "Pondicherry University",
      "Dr BR Amebdkar University Delhi",
    ],
    howToApply: [
      "Interested Candidates Can Read the NCET Exam 2025 Full Notification Before Apply Online.",
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Check Exam City Details", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Date Extended Notice", url: "#" },
      { label: "Download Notification", url: "#" },
      { label: "Download Syllabus", url: "#" },
      { label: "Download University Wise Course List", url: "#" },
      { label: "Image Resizer, JPG to PDF and Other Tools", url: "#" },
      { label: "Join Sarkari Result Channel", url: "Telegram | WhatsApp" },
      { label: "Official Website", url: "NTA NCET 2025 Official Website" },
    ],
  },
  {
    id: 6,
    text: "NIELIT CCC Exam Admit Card 2025 for April 2025 Exam",
    postDate: "22 April 2025 | 06:15 PM",
    shortInfo:
      "National Institute of Electronics and Information Technology NIELIT Course on Computer Concepts (CCC) Exam March 2025 Admit Card Released. Those candidates who are Enrolled in NIELIT CCC Exam April 2025 Can Download the Hall Ticket / Admit Card. Read the CCC Exam Instruction Before Going to Venue for NIELIT CCC Examination 2025, Also Check and Download Syllabus, Exam Pattern, Result, Certificate on Official Student.Nielit Website.",
    importantDates: {
      cccExamDate: "April 2025",
      admitCardAvailable: "Before Exam",
    },
    applicationFee: {
      generalOtherState: "0/-",
      obcBc: "0/-",
      scSt: "0/-",
      note: "No Application Fee to Download the CCC Exam Admit Card.",
    },
    conductedBy:
      "The CCC exam is organized by the National Institute of Electronics and Information Technology (NIELIT), Ministry of Electronics and Information Technology, Government of India.",
    howToDownload: [
      "Step 1: First of all, you will see the link of download admit card in the Some Useful Important Link section at the bottom of this page, you have to click on it.",
      "Step 2: A new page student.nielit.gov.in will open.",
      "Step 3: In the new page that has been opened, on the right side you will get the link of download admit card, you have to click on it.",
      "Step 4: Now you see the name of all the courses organized by NIELIT, in that you have to select Course on Computer Concepts (CCC) in IT Literacy Program section.",
      "Step 5: Now you will see an undertaking, you have to read it and then.",
      "Step 6: Now you have to select the exam year, after that you have to select the month of the exam. In the last, you have to enter your application number along with your date of birth, after filling the Captcha code given on the page, you will see the button of View and then you will get the button of print admit card, you have to click on it.",
      "Step 7: The admit card of NIELIT CCC exam will now be shown on your screen, now you can print it in color or black and white. Also, if you do not have a printer available, you can save it and take a print out before the exam.",
      "Step 8: Before going to NIELIT CCC exam, read carefully all the instructions given in the admit card such as exam date, reporting time, gate closing time, original valid photo identity card related information and other NIELIT CCC exam instructions you will get in the admit card.",
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "Server I | Server II" },
      { label: "Check Form Status", url: "CCC Form Status" },
      { label: "Download Syllabus", url: "CCC Exam Syllabus" },
      { label: "Join Sarkari Result Channel", url: "Telegram | WhatsApp" },
      { label: "Official Website", url: "NIELIT Official Website" },
    ],
  },
  {
    id: 7,
    text: "NTA Joint Integrated Program in Management JIPMAT Admissions 2025 Admit Card",
    postDate: "22 April 2025 | 06:13 PM",
    shortInfo:
      "National Testing Agency (NTA) has released the Joint Integrated Program in Management JIPMAT 2025 online application for admission 2025 will start from 11 February 2025 and the last date to apply will be 17 March 2025. Various Institution are participating in JIPMAT 2025, candidates should read the information brochure for all the information related to the entrance exam like syllabus, eligibility, age limit, placement, fees, college information and other types of information and then apply.",
    importantDates: {
      applicationBegin: "11/02/2025",
      lastDateApplyOnline: "17/03/2025",
      payExamFeeLastDate: "18/03/2025",
      correctionDate: "19-21 March 2025",
      examDate: "26/04/2025",
      examCityAvailable: "17/04/2025",
      admitCardAvailable: "22/04/2025",
    },
    applicationFee: {
      generalObcEws: "2000/-",
      scStPh: "1000/-",
      paymentMode:
        "Pay the Exam Fee Through Debit Card, Credit Card, Net Banking, UPI or E Challan",
    },
    admissionDetails: {
      courseName:
        "Joint Integrated Program in Management Admission Test JIPMAT 2025 (IIM Bodh Gaya & IIM Jammu)",
      eligibility:
        "10+2 Intermediate Exam with Minimum 60% Marks. For SC / ST Candidates Required: 55% Marks.",
    },
    howToApply: [
      "National Testing Agency NTA Are Released Notification for JIPMAT Entrance Test 2025, Candidate Can Apply Between 11/02/2025 to 17/03/2025.",
      "Candidate Read the Notification Before Apply the Admission Application Form in JIPMAT Admission 2025.",
      "Kindly Check and Collect the All Document - Eligibility, ID Proof, Address Details, Basic Details.",
      "Kindly Ready Scan Document Related to Recruitment Form - Photo, Sign, ID Proof, Etc.",
      "Before Submit the Application Form Must Check the Preview and All Column Carefully.",
      "If Candidate Required to Paying the Application Fee Must Submit. If You have Not the Required Application Fees Your Form is Not Completed.",
      "Take A Print Out of Final Submitted Form.",
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Check Exam City Details", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "For Correction / Edit Form", url: "#" },
      { label: "Download Correction Notice", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Date Extension Notice", url: "#" },
      { label: "Download Notification", url: "JIPMAT Information Brochure" },
    ],
  },
  {
    id: 9,
    text: "Railway Recruitment Board RRB Assistant Loco Pilot ALP CEN 01/2024 Download Stage II City Details 2025 for 18799 Post",
    postDate: "22 April 2025 | 06:03 PM",
    shortInfo:
      "Indian Railway (Railway Recruitment Board) has released Assistant Loco Pilot ALP Recruitment 2024. Those candidates who are interested in this RRB Prayagraj, RRB Gorakhpur, RRB Ajmer, RRB Kolkata, RRB Mumbai, RRB Secunderabad, RRB Chennai and Other recruitment can Download Answer Key and Objection Link. Read the notification for recruitment eligibility, post information, selection procedure, age limit, pay scale and all other information.",
    importantDates: {
      applicationBegin: "20/01/2024",
      lastDateApplyOnline: "19/02/2024",
      lastDatePayExamFee: "19/02/2024",
      correctionModifiedForm: "20-29 February 2024",
      reUploadPhotoSignature: "27-31 May 2024",
      zoneWiseRevisedVacancyDetails: "04/07/2024",
      changeZonePreferencesOnline: "29/07/2024 to 07/08/2024",
      cbtExamDate: "25-29 November 2024",
      examCityAvailable: "10 Days Before Exam",
      admitCardAvailable: "4 Days Before Exam",
      answerKeyAvailable: "05/12/2024",
      stageIICbtExamDate: "19-20 March 2025",
      stageIICbtRescheduleExamDate: "02-06 May 2025",
      stageIIExamCityAvailable: "22/04/2025",
    },
    applicationFee: {
      generalObcEws: "500/-",
      ebc: "250/-",
      allCategoryFemale: "250/-",
      feeRefund: {
        generalObcEws: "400/-",
        scStEbcFemale: "250/-",
      },
      paymentMode:
        "Pay the Examination Fee Through Debit Card, Credit Card, Net Banking Fee Mode Only.",
    },
    ageLimit: {
      minimumAge: "18 Years",
      maximumAge: "33 Years",
      ageRelaxation:
        "Extra as per Railway Recruitment Board RRB ALP Recruitment Advt No. CEN 01/2024 Vacancy Rules.",
    },
    vacancyDetails: {
      totalPost: 18799,
      categoryWise: {
        ur: 8149,
        obc: 4538,
        ews: 1798,
        sc: 2735,
        st: 1579,
      },
      eligibility:
        "Class 10th Matric with ITI from NCVT / SCVT Certificate in Fitter, Electrician, Instrument Mechanic, Millwright, Maintenance Mechanic, Mechanic Radio and TV, Electronics Mechanic, Mechanic Motor Vehicle, Wireman, Tractor Mechanic, Armature and Coil Winder, Mechanic Diesel, Heat Engine, Turner, Machinist, Refrigeration and AC OR Class 10th with Diploma in Mechanical / Electrical / Electronics / Automobile Engineering OR BE / B.Tech Degree in Mechanical / Electrical / Electronics / Automobile Engineering. More Eligibility Details Read the Notification.",
    },
    zoneWiseVacancyDetails: [
      {
        rrbName: "RRB Ahemdabad WR",
        ur: 394,
        sc: 132,
        st: 67,
        obc: 244,
        ews: 100,
        total: 937,
      },
      {
        rrbName: "RRB Ajmer NWR",
        ur: 314,
        sc: 113,
        st: 56,
        obc: 204,
        ews: 74,
        total: 761,
      },
      {
        rrbName: "RRB Bangalore SWR",
        ur: 640,
        sc: 235,
        st: 118,
        obc: 426,
        ews: 157,
        total: 1576,
      },
      {
        rrbName: "RRB Bhopal WCR",
        ur: 466,
        sc: 87,
        st: 62,
        obc: 52,
        ews: 62,
        total: 729,
      },
      {
        rrbName: "RRB Bhopal WR",
        ur: 42,
        sc: 15,
        st: 7,
        obc: 27,
        ews: 10,
        total: 101,
      },
      {
        rrbName: "RRB Bhubaneswar ECOR",
        ur: 412,
        sc: 141,
        st: 68,
        obc: 254,
        ews: 55,
        total: 930,
      },
      {
        rrbName: "RRB Bilaspur CR",
        ur: 251,
        sc: 21,
        st: 52,
        obc: 96,
        ews: 42,
        total: 462,
      },
      {
        rrbName: "RRB Bilaspur SECR",
        ur: 1610,
        sc: 595,
        st: 298,
        obc: 1072,
        ews: 398,
        total: 3973,
      },
      {
        rrbName: "RRB Chandigarh NR",
        ur: 170,
        sc: 22,
        st: 13,
        obc: 87,
        ews: 32,
        total: 324,
      },
      {
        rrbName: "RRB Chennai SR",
        ur: 182,
        sc: 105,
        st: 43,
        obc: 105,
        ews: 58,
        total: 493,
      },
      // Add more zone-wise details as needed
    ],
    howToApply: [
      "Railway Recruitment Board RRB Online Released Assistant Loco Pilot ALP Recruitment Advt No. CEN 01/2024 Exam. Candidate Can Apply Between 20/01/2024 to 19/02/2024.",
      "Candidate Read the Notification Before Apply the Recruitment Application Form in Railway Board ALP Exam 2024 Advt No. 01/2024 Exam Online Form 2024.",
      "Kindly Check and Collect the All Document - Eligibility, ID Proof, Address Details, Basic Details.",
      "Kindly Ready Scan Document Related to Admission Entrance Form - Photo, Sign, ID Proof, Etc.",
      "Before Submit the Application Form Must Check the Preview and All Column Carefully.",
      "Take A Print Out of Final Submitted Form.",
    ],
    importantLinks: [
      { label: "Check Exam City Details", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "Download Stage II Reschedule Exam Notice", url: "#" },
      { label: "Download Admit Card", url: "#" },
      { label: "Download Stage II Re Schedule Notice", url: "#" },
      { label: "How to Check Exam City & Date (Video Hindi)", url: "#" },
      { label: "Download Stage I Result", url: "#" },
      { label: "Download Stage II Exam Notice", url: "#" },
      { label: "Download Answer Key", url: "Server I | Server II" },
      {
        label: "How to Check Answer Key & File Objection (Video Hindi)",
        url: "#",
      },
      { label: "Download Answer Key Notice", url: "#" },
      { label: "Download Objection Guide", url: "#" },
      { label: "Mock Test Practice", url: "#" },
      { label: "Download Exam Notice", url: "#" },
      { label: "For Aadhar Verification", url: "#" },
      { label: "Download Aadhar Verification Notice", url: "Hindi | English" },
      { label: "For Change Preferences / Status", url: "#" },
      { label: "Download Change / Update Preferences Notice", url: "#" },
      {
        label: "Download RRB Zone Wise Vacancy Increase Notice",
        url: "English | Hindi",
      },
      { label: "Download Vacancy Increase Notice", url: "English | Hindi" },
      { label: "Re Upload Photo / Signature", url: "#" },
      { label: "Download Notice for Re Upload Photo / Signature", url: "#" },
      { label: "For Correction / Edit Form", url: "#" },
      { label: "Apply Online", url: "Registration | Login" },
      { label: "Download Notification", url: "English | Hindi" },
      { label: "Download Syllabus", url: "#" },
      {
        label: "RRB Photo Resizer, Marriage Bio Data Maker and More Tools",
        url: "#",
      },
      { label: "Join Sarkari Result Channel", url: "Telegram | WhatsApp" },
      { label: "ALP Recruitment Website", url: "Government employment" },
      {
        label: "Railway ALP Recruitment Official Website",
        url: "Official Website",
      },
      { label: "Indian Railway Official Website", url: "Official Website" },
    ],
  },
  {
    id: 10,
    text: "UPSSSC Gram Panchayat Adhikari Recruitment 2023 Mains Check Exam City Details, Admit Card 2025 for 1468 Post",
    postDate: "24 April 2025 | 06:08 PM",
    shortInfo:
      "Uttar Pradesh Subordinate Service Selection Commission (UPSSSC) has released the Gram Panchayat Adhikari recruitment advertisement for 1468 posts. Those candidates who are Enrolled with Vacancy Can Check the Exam Admit Card Details 2025. Read the notification for recruitment eligibility, post information, selection procedure, age limit, pay scale and all other information.",
    importantDates: {
      applicationBegin: "23/05/2023",
      lastDateRegistration: "12/06/2023",
      feePaymentLastDate: "12/06/2023",
      correctionLastDate: "19/06/2023",
      eligibilityResult: "27/09/2023",
      mainsFeePaymentStart: "03/04/2025",
      examDate: "27/04/2025",
      examCityAvailable: "21/04/2025",
      admitCardAvailable: "24/04/2025",
    },
    applicationFee: {
      generalObcEws: "25/-",
      scSt: "25/-",
      ph: "25/-",
      paymentMode:
        "Pay the Examination Fee Through State Bank of India SBI I Collect Fee Mode or Pay the Exam Fee Through E Challan",
    },
    ageLimit: {
      minimumAge: "18 Years",
      maximumAge: "40 Years",
      ageRelaxation:
        "Extra as per UPSSSC UP Gram Panchayat Adhikari VDO Recruitment Advt No. 01/2023 Rules",
    },
    vacancyDetails: {
      totalPost: 1468,
      eligibility:
        "UPSSSC PET 2022 Score Card. 10+2 Intermediate Exam in Any Recognized Board In India with CCC / Equivalent Exam Passed.",
    },
    categoryWiseVacancy: [
      {
        postName: "Gram Panchayat Adhikari",
        ur: 849,
        ews: 117,
        obc: 139,
        sc: 356,
        st: 7,
        total: 1468,
      },
    ],
    howToApply: [
      "There are 02 types to apply online for UPSSSC 10+2 Gram Panchayat Adhikari Advt No. 01-Exam/2023 Recruitment 2023.",
      "First: In this, the candidate will have to login with his personal information, the information that has to be given is: PET Registration Number, Date of Birth, Gender, Domicile and Category.",
      "Second: In this, the candidate will have to login through his OTP, the information that has to be given is: UPSSSC PET 2022 Registration Number and OTP Password.",
      "After login, the complete information of the candidate, his photo and signature will also be visible, the candidate will have to fill the information related to the post he is asking for and the application fee: Rs.25/- will have to be paid.",
      "Kindly Check and Collect the All Document - Eligibility, ID Proof, Address Details, Basic Details.",
      "Kindly Ready Scan Document Related to Recruitment Form - Photo, Sign, ID Proof, Etc.",
      "Before Apply Online / Submit Application Form Must Check the Preview and All Column Carefully.",
      "Take A Print Out of Final Submitted Form.",
    ],
    importantLinks: [
      { label: "Download Admit Card", url: "#" },
      { label: "Download Admit Card Notice", url: "#" },
      { label: "Check Exam City Details", url: "#" },
      { label: "Download Exam City Notice", url: "#" },
      { label: "Pay Mains Exam Fee", url: "#" },
      { label: "Download Mains Fee Payment Notice", url: "#" },
      { label: "Download Exam Notice", url: "#" },
      { label: "Download Eligibility Result", url: "#" },
      { label: "Download Eligibility Result Notice", url: "#" },
      { label: "Apply Online", url: "#" },
      { label: "Download Notification", url: "#" },
      {
        label:
          "Resume CV Maker, Image Resizer, JPG to PDF Converter, Typing Test Practice, More",
        url: "#",
      },
      { label: "Join Our Telegram Page", url: "#" },
      { label: "Official Website", url: "UPSSSC Official Website" },
    ],
  },
];

export default Data;
